-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 16-05-2021 a las 16:25:15
-- Versión del servidor: 5.6.17
-- Versión de PHP: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `feedrss`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `feeds`
--

CREATE TABLE IF NOT EXISTS `feeds` (
  `IdFeed` int(11) NOT NULL AUTO_INCREMENT,
  `Image_link` text,
  `Image_title` text,
  `Image_url` text,
  `Image_width` int(11) DEFAULT NULL,
  `Image_height` int(11) DEFAULT NULL,
  `Imagelink` text,
  `Permalink` text,
  `Title` varchar(120) DEFAULT NULL,
  `Description` varchar(120) DEFAULT NULL,
  `Sourcepermalink` text,
  `Sourcetitle` text,
  `Date` datetime DEFAULT NULL,
  `Categories` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`IdFeed`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=39 ;

--
-- Volcado de datos para la tabla `feeds`
--

INSERT INTO `feeds` (`IdFeed`, `Image_link`, `Image_title`, `Image_url`, `Image_width`, `Image_height`, `Imagelink`, `Permalink`, `Title`, `Description`, `Sourcepermalink`, `Sourcetitle`, `Date`, `Categories`) VALUES
(1, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMihAFodHRwczovL3d3dy5jYnNzcG9ydHMuY29tL2dvbGYvbmV3cy8yMDIxLWF0LXQtYnlyb24tbmVsc29uLWxlYWRlcmJvYXJkLWxpdmUtY292ZXJhZ2UtZ29sZi1zY29yZXMtdXBkYXRlcy1oaWdobGlnaHRzLWluLXJvdW5kLTQvbGl2ZS_SAYgBaHR0cHM6Ly93d3cuY2Jzc3BvcnRzLmNvbS9nb2xmL25ld3MvMjAyMS1hdC10LWJ5cm9uLW5lbHNvbi1sZWFkZXJib2FyZC1saXZlLWNvdmVyYWdlLWdvbGYtc2NvcmVzLXVwZGF0ZXMtaGlnaGxpZ2h0cy1pbi1yb3VuZC00L2xpdmUvYW1wLw?oc=5', '2021 AT&amp;T Byron Nelson leaderboard: Live coverage, golf scores, updates, highlights in Round 4 - CBSSports.com', '2021 AT&amp;T Byron Nelson leaderboard: Live coverage, golf scores, updates, highlights in Round 4  CBSSports.com Jordan', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 14:43:00', ''),
(2, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vd3d3Lmlnbi5jb20vYXJ0aWNsZXMvY2hpbmEtaGFzLXN1Y2Nlc3NmdWxseS1sYW5kZWQtaXRzLW93bi1tYXJzLXJvdmVy0gFTaHR0cHM6Ly93d3cuaWduLmNvbS9hcnRpY2xlcy9jaGluYS1oYXMtc3VjY2Vzc2Z1bGx5LWxhbmRlZC1pdHMtb3duLW1hcnMtcm92ZXI_YW1wPTE?oc=5', 'China Has Successfully Landed Its Own Mars Rover - IGN - IGN', 'China Has Successfully Landed Its Own Mars Rover - IGN  IGN NASA\\''s Perseverance rover captured more striking photos of ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 14:22:10', ''),
(3, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3LnlhaG9vLmNvbS9lbnRlcnRhaW5tZW50L3JpY2t5LXNjaHJvZGVyLWNvbmZyb250cy1jb3N0Y28tZW1wbG95ZWUtbWFzay1yZXF1aXJlbWVudC0xODQ1MTczMTcuaHRtbNIBdGh0dHBzOi8vd3d3LnlhaG9vLmNvbS9hbXBodG1sL2VudGVydGFpbm1lbnQvcmlja3ktc2Nocm9kZXItY29uZnJvbnRzLWNvc3Rjby1lbXBsb3llZS1tYXNrLXJlcXVpcmVtZW50LTE4NDUxNzMxNy5odG1s?oc=5', 'Ricky Schroder confronts Costco employee over mask requirement in viral video: \\''You\\''re just going to listen to their r', 'Ricky Schroder confronts Costco employee over mask requirement in viral video: \\''You\\''re just going to listen to their r', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 13:45:17', ''),
(4, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiogFodHRwczovL3d3dy5mcmVlcC5jb20vc3Rvcnkvc3BvcnRzL2NvbGxlZ2UvdW5pdmVyc2l0eS1taWNoaWdhbi93b2x2ZXJpbmVzLzIwMjEvMDUvMTYvY2hyaXMtd2ViYmVyLWphbGVuLXJvc2UtYmVlZi1mYWItZml2ZS1taWNoaWdhbi1iYXNrZXRiYWxsLWRldHJvaXQvNTEyMDQwOTAwMS_SAQA?oc=5', 'Chris Webber and Jalen Rose reunite, publicly end longtime Michigan Fab Five feud - Detroit Free Press', 'Chris Webber and Jalen Rose reunite, publicly end longtime Michigan Fab Five feud  Detroit Free PressView Full Coverage ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 13:41:35', ''),
(5, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjEvMDUvMTYvd29ybGQvY2RjLWRpcmVjdG9yLXVudmFjY2luYXRlZC1tYXNrcy5odG1s0gFRaHR0cHM6Ly93d3cubnl0aW1lcy5jb20vMjAyMS8wNS8xNi93b3JsZC9jZGMtZGlyZWN0b3ItdW52YWNjaW5hdGVkLW1hc2tzLmFtcC5odG1s?oc=5', 'Unvaccinated People Are Most at Risk by Unmasking, C.D.C. Director Says - The New York Times', 'Unvaccinated People Are Most at Risk by Unmasking, C.D.C. Director Says  The New York Times Fauci defends CDC\\''s roundab', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 13:30:48', ''),
(6, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiXmh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjEvMDUvMTYvYXR0LWluLWFkdmFuY2VkLXRhbGtzLXRvLW1lcmdlLXdhcm5lcm1lZGlhLXdpdGgtZGlzY292ZXJ5Lmh0bWzSAWJodHRwczovL3d3dy5jbmJjLmNvbS9hbXAvMjAyMS8wNS8xNi9hdHQtaW4tYWR2YW5jZWQtdGFsa3MtdG8tbWVyZ2Utd2FybmVybWVkaWEtd2l0aC1kaXNjb3ZlcnkuaHRtbA?oc=5', 'AT&amp;T in advanced talks to merge WarnerMedia with Discovery, deal expected as soon as tomorrow - CNBC', 'AT&amp;T in advanced talks to merge WarnerMedia with Discovery, deal expected as soon as tomorrow  CNBC AT&amp;T and Dis', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:57:48', ''),
(7, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiW2h0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIxLzUvMTYvMjI0MzkwMzIvY2x1YmhvdXNlLWV4cGFuZGluZy1hbmRyb2lkLWFwcC1jb3VudHJpZXMtYXVkaW_SAWhodHRwczovL3d3dy50aGV2ZXJnZS5jb20vcGxhdGZvcm0vYW1wLzIwMjEvNS8xNi8yMjQzOTAzMi9jbHViaG91c2UtZXhwYW5kaW5nLWFuZHJvaWQtYXBwLWNvdW50cmllcy1hdWRpbw?oc=5', 'Clubhouse expanding its new Android app to more countries this week - The Verge', 'Clubhouse expanding its new Android app to more countries this week  The VergeView Full Coverage on Google News', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:41:20', ''),
(8, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vbnlwb3N0LmNvbS8yMDIxLzA1LzE2L2RhbW9uLXdlYXZlci1raWQtcmVwb3J0ZXItd2hvLWludGVydmlld2VkLW9iYW1hLWF0LXdoaXRlLWhvdXNlLWRlYWQtYXQtMjMv0gFsaHR0cHM6Ly9ueXBvc3QuY29tLzIwMjEvMDUvMTYvZGFtb24td2VhdmVyLWtpZC1yZXBvcnRlci13aG8taW50ZXJ2aWV3ZWQtb2JhbWEtYXQtd2hpdGUtaG91c2UtZGVhZC1hdC0yMy9hbXAv?oc=5', 'Damon Weaver, kid reporter who interviewed Obama at White House, dead at 23 - New York Post', 'Damon Weaver, kid reporter who interviewed Obama at White House, dead at 23  New York Post Child reporter who interviewe', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:37:00', ''),
(9, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMifmh0dHBzOi8vd3d3Lm5wci5vcmcvMjAyMS8wNS8xNi85OTczMDM2NTcvaXNyYWVsaS1haXJzdHJpa2VzLW9uLWdhemEtY29udGludWUtYWZ0ZXItZ2xvYmFsLXByby1wYWxlc3Rpbmlhbi1wcm90ZXN0cz9mdD1ucHJtbCZmPdIBAA?oc=5', 'Israeli Airstrikes On Gaza Continue After Global Pro-Palestinian Protests - NPR', 'Israeli Airstrikes On Gaza Continue After Global Pro-Palestinian Protests  NPR Israel air strike targets Hamas leader - ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:19:12', ''),
(10, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIxLTA1LTE2L2Vsb24tbXVzay1qdXN0LXJlb3BlbmVkLWFuLW9sZC13b3VuZC1pbi10aGUtYml0Y29pbi13b3JsZNIBAA?oc=5', 'Elon Musk Just Reopened an Old Wound in the Bitcoin World - Bloomberg', 'Elon Musk Just Reopened an Old Wound in the Bitcoin World  Bloomberg Musk’s Latest Dogecoin Tweet Sparks Fierce CEO Resp', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:05:54', ''),
(11, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiWGh0dHBzOi8vYWJjN25ld3MuY29tL2Zhc3QtbW92aW5nLXdpbGRmaXJlLWluLWxvcy1hbmdlbGVzLWV4cGxvZGVzLXRoaXMtd2Vla2VuZC8xMDY0NDQ4MC_SAV1odHRwczovL2FiYzduZXdzLmNvbS9hbXAvcGFjaWZpYy1wYWxpc2FkZXMtZmlyZS1sb3MtYW5nZWxlcy13aWxkZmlyZS1sYS1ldmFjdWF0aW9ucy8xMDY0NDQ4MC8?oc=5', 'Pacific Palisades fire: Fast-moving wildfire in Southern California explodes this weekend, forcing mandatory evacuations', 'Pacific Palisades fire: Fast-moving wildfire in Southern California explodes this weekend, forcing mandatory evacuations', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:03:45', ''),
(12, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiXWh0dHBzOi8vd3d3LnBvbGl0aWNvLmNvbS9uZXdzLzIwMjEvMDUvMTYvZ2lsbGlicmFuZC1lcm5zdC1taWxpdGFyeS1zZXh1YWwtYXNzYXVsdC1iaWxsLTQ4ODY2N9IBYWh0dHBzOi8vd3d3LnBvbGl0aWNvLmNvbS9hbXAvbmV3cy8yMDIxLzA1LzE2L2dpbGxpYnJhbmQtZXJuc3QtbWlsaXRhcnktc2V4dWFsLWFzc2F1bHQtYmlsbC00ODg2Njc?oc=5', 'Senators tout bipartisan effort to combat sexual assault in military - POLITICO', 'Senators tout bipartisan effort to combat sexual assault in military  POLITICOView Full Coverage on Google News', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 12:03:11', ''),
(13, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiYWh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvYmF0dGVyaWVzLWNoYWxsZW5nZS1uYXR1cmFsLWdhcy1lbGVjcmljLXBvd2VyLWdlbmVyYXRpb24tMTE2MjAyMzY1ODPSAQA?oc=5', 'Natural Gas, America’s No. 1 Power Source, Already Has a New Challenger: Batteries - The Wall Street Journal', 'Natural Gas, America’s No. 1 Power Source, Already Has a New Challenger: Batteries  The Wall Street Journal', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 11:55:00', ''),
(14, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL21pZGRsZS1lYXN0LWlzcmFlbC1yZWxpZ2lvbi1jNDVhZjUwNDFiYjMxZTkzMmUyYzU1OTUwZGI3NjNiY9IBAA?oc=5', 'Israeli paramedics: 2 dead in synagogue bleacher collapse - The Associated Press', 'Israeli paramedics: 2 dead in synagogue bleacher collapse  The Associated Press Israeli emergency services responding to', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 11:41:45', ''),
(15, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMid2h0dHBzOi8vdGhlaGlsbC5jb20vcG9saWN5L2ludGVybmF0aW9uYWwvYXNpYS1wYWNpZmljLzU1Mzc3NC1hdXRob3JpdGllcy1pbi1pbmRpYS1kaXNjb3Zlci1odW5kcmVkcy1vZi1ib2RpZXMtYnVyaWVkLWlu0gF7aHR0cHM6Ly90aGVoaWxsLmNvbS9wb2xpY3kvaW50ZXJuYXRpb25hbC9hc2lhLXBhY2lmaWMvNTUzNzc0LWF1dGhvcml0aWVzLWluLWluZGlhLWRpc2NvdmVyLWh1bmRyZWRzLW9mLWJvZGllcy1idXJpZWQtaW4_YW1w?oc=5', 'Authorities in India discover hundreds of bodies buried in riverbanks | TheHill - The Hill', 'Authorities in India discover hundreds of bodies buried in riverbanks | TheHill  The Hill Hundreds of bodies found burie', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 11:40:56', ''),
(16, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiJGh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy91ay01NzEzNDE4MdIBAA?oc=5', 'Covid: Increasing confidence jabs work against Indian variant - BBC News', 'Covid: Increasing confidence jabs work against Indian variant  BBC News Matt Hancock: unlocking will go ahead next week ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 10:58:46', ''),
(17, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vdmFyaWV0eS5jb20vMjAyMS9maWxtL25ld3MvdGhvc2Utd2hvLXdpc2gtbWUtZGVhZC1ib3gtb2ZmaWNlLXNwaXJhbC0xMjM0OTc0MDY3L9IBW2h0dHBzOi8vdmFyaWV0eS5jb20vMjAyMS9maWxtL25ld3MvdGhvc2Utd2hvLXdpc2gtbWUtZGVhZC1ib3gtb2ZmaWNlLXNwaXJhbC0xMjM0OTc0MDY3L2FtcC8?oc=5', 'Box Office: Angelina Jolie’s ‘Those Who Wish Me Dead’ DOA as ‘Spiral’ Claims No. 1 - Variety', 'Box Office: Angelina Jolie’s ‘Those Who Wish Me Dead’ DOA as ‘Spiral’ Claims No. 1  Variety Angelina Jolie returns to th', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 10:53:00', ''),
(18, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMieGh0dHBzOi8vd3d3Lm5iY25ld3MuY29tL25ld3MvdXMtbmV3cy92YW5lc3NhLWJyeWFudC1naXZlcy1wb3dlcmZ1bC1zcGVlY2gtaW5kdWN0aW5nLWtvYmUtYnJ5YW50LWJhc2tldGJhbGwtaGFsbC1uMTI2NzUyNNIBLGh0dHBzOi8vd3d3Lm5iY25ld3MuY29tL25ld3MvYW1wL25jbmExMjY3NTI0?oc=5', 'Vanessa Bryant gives powerful speech inducting Kobe Bryant into Basketball Hall of Fame - NBC News', 'Vanessa Bryant gives powerful speech inducting Kobe Bryant into Basketball Hall of Fame  NBC News \\''He\\''s still winning\\', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 10:12:00', ''),
(19, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiXGh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIxLzUvMTYvMjI0Mzg4NDIvYW1hem9uLWZyZWUtdmlkZW8tc3RyZWFtaW5nLXNlcnZpY2UtbWluaXR2LWluZGlh0gFpaHR0cHM6Ly93d3cudGhldmVyZ2UuY29tL3BsYXRmb3JtL2FtcC8yMDIxLzUvMTYvMjI0Mzg4NDIvYW1hem9uLWZyZWUtdmlkZW8tc3RyZWFtaW5nLXNlcnZpY2UtbWluaXR2LWluZGlh?oc=5', 'Amazon debuts free video-streaming service MiniTV in its India app - The Verge', 'Amazon debuts free video-streaming service MiniTV in its India app  The Verge Amazon Prime Video: The 24 best movies to ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 10:09:21', ''),
(20, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMigwFodHRwczovL3d3dy5iZW56aW5nYS5jb20vbmV3cy8yMS8wNS8yMTE0MzE2MC90d2l0dGVyLW1heS1iZS1nZWFyaW5nLXVwLXRvLWxhdW5jaC10d2l0dGVyLWJsdWUtc3Vic2NyaXB0aW9uLW1vZHVsZS1hdC0yLTk5LXBlci1tb250aNIBAA?oc=5', 'Twitter May Be Gearing Up To Launch Twitter Blue Subscription Module At $2.99 Per Month - Benzinga', 'Twitter May Be Gearing Up To Launch Twitter Blue Subscription Module At $2.99 Per Month  Benzinga Twitter to call subscr', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 09:50:00', ''),
(21, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiVmh0dHBzOi8vYWJjMTEuY29tL25jLWdhcy1zaG9ydGFnZS11cGRhdGUtd2hlcmUtdG8tZmluZC1uZWFyLW1lLWJ1ZGR5LXN0YXRpb24vMTA2NDM4MTkv0gFaaHR0cHM6Ly9hYmMxMS5jb20vYW1wL25jLWdhcy1zaG9ydGFnZS11cGRhdGUtd2hlcmUtdG8tZmluZC1uZWFyLW1lLWJ1ZGR5LXN0YXRpb24vMTA2NDM4MTkv?oc=5', 'NC gas shortage update: Colonial Pipeline returns to normal operations but majority of North Carolina gas stations witho', 'NC gas shortage update: Colonial Pipeline returns to normal operations but majority of North Carolina gas stations witho', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 09:42:14', ''),
(22, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiQWh0dHBzOi8vd3d3LmNic25ld3MuY29tL25ld3MvcmVwdWJsaWNhbnMtbGl6LWNoZW5leS1vcGluaW9uLXBvbGwv0gFFaHR0cHM6Ly93d3cuY2JzbmV3cy5jb20vYW1wL25ld3MvcmVwdWJsaWNhbnMtbGl6LWNoZW5leS1vcGluaW9uLXBvbGwv?oc=5', 'Republicans weigh in on Liz Cheney and direction of GOP — CBS News poll - CBS News', 'Republicans weigh in on Liz Cheney and direction of GOP — CBS News poll  CBS News Chris Wallace presses Liz Cheney on Tr', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 09:30:00', ''),
(23, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiZ2h0dHBzOi8vd3d3LnJvbGxpbmdzdG9uZS5jb20vbXVzaWMvbXVzaWMtbmV3cy9qb25pLW1pdGNoZWxsLWNsaXZlLWRhdmlzLWdyYW1teS1wYXJ0eS1pbnRlcnZpZXctMTE3MDIxMC_SAWtodHRwczovL3d3dy5yb2xsaW5nc3RvbmUuY29tL211c2ljL211c2ljLW5ld3Mvam9uaS1taXRjaGVsbC1jbGl2ZS1kYXZpcy1ncmFtbXktcGFydHktaW50ZXJ2aWV3LTExNzAyMTAvYW1wLw?oc=5', 'Joni Mitchell Gives Rare Interview at Clive Davis’ Virtual Grammy Party - Rolling Stone', 'Joni Mitchell Gives Rare Interview at Clive Davis’ Virtual Grammy Party  Rolling Stone Joni Mitchell says making more pe', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 09:04:57', ''),
(24, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3LnVzYXRvZGF5LmNvbS9zdG9yeS9uZXdzL25hdGlvbi8yMDIxLzA1LzE2L2hvdXN0b24tdGlnZXItbmFtZWQtaW5kaWEtZm91bmQtc2FmZS1zZW50LXNhbmN0dWFyeS81MTE4NDM3MDAxL9IBJ2h0dHBzOi8vYW1wLnVzYXRvZGF5LmNvbS9hbXAvNTExODQzNzAwMQ?oc=5', 'Houston\\''s elusive tiger named India found safe, headed for sanctuary - USA TODAY', 'Houston\\''s elusive tiger named India found safe, headed for sanctuary  USA TODAY Tiger missing in Houston turned in to a', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 08:50:34', ''),
(25, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiZmh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjEvMDUvMTYvd2F0Y2gtbGl2ZS1kci1hbnRob255LWZhdWNpLXNwZWFrcy1hdC1lbW9yeS11bml2ZXJzaXR5LWdyYWR1YXRpb24uaHRtbNIBamh0dHBzOi8vd3d3LmNuYmMuY29tL2FtcC8yMDIxLzA1LzE2L3dhdGNoLWxpdmUtZHItYW50aG9ueS1mYXVjaS1zcGVha3MtYXQtZW1vcnktdW5pdmVyc2l0eS1ncmFkdWF0aW9uLmh0bWw?oc=5', 'Dr. Anthony Fauci to Emory University graduates: Embrace change and \\''expect the unexpected\\'' - CNBC', 'Dr. Anthony Fauci to Emory University graduates: Embrace change and \\''expect the unexpected\\''  CNBC Fauci says pandemic ', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 08:45:01', ''),
(26, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIxLTA1LTE2L2JyYXppbC1zLXNhby1wYXVsby1tYXlvci1icnVuby1jb3Zhcy1kaWVzLW9mLWNhbmNlci1hdC00MdIBAA?oc=5', 'Brazil\\''s Sao Paulo Mayor Bruno Covas Dies of Cancer at 41 - Bloomberg', 'Brazil\\''s Sao Paulo Mayor Bruno Covas Dies of Cancer at 41  BloombergView Full Coverage on Google News', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 08:14:47', ''),
(27, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9b3d2NW1mUWtOT0XSAQA?oc=5', 'COVID-19: Experts Believe Some Pockets Of San Francisco Bay Area May Already Have Herd Immunity - KPIX CBS SF Bay Area', 'COVID-19: Experts Believe Some Pockets Of San Francisco Bay Area May Already Have Herd Immunity  KPIX CBS SF Bay Area Tw', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 08:02:52', ''),
(28, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMigAFodHRwczovL3d3dy53YXNoaW5ndG9ucG9zdC5jb20vaGVhbHRoL2JyYWluLWZvZy1tZW5vcGF1c2UtbWVtb3J5LWxvc3MvMjAyMS8wNS8xNC8wNjAwYzA4OC1hZWE2LTExZWItYWI0Yy05ODY1NTVhMWM1MTFfc3RvcnkuaHRtbNIBjwFodHRwczovL3d3dy53YXNoaW5ndG9ucG9zdC5jb20vaGVhbHRoL2JyYWluLWZvZy1tZW5vcGF1c2UtbWVtb3J5LWxvc3MvMjAyMS8wNS8xNC8wNjAwYzA4OC1hZWE2LTExZWItYWI0Yy05ODY1NTVhMWM1MTFfc3RvcnkuaHRtbD9vdXRwdXRUeXBlPWFtcA?oc=5', 'As menopause approaches, some women suffer ‘brain fog’ and memory loss. What’s causing these problems? - The Washington ', 'As menopause approaches, some women suffer ‘brain fog’ and memory loss. What’s causing these problems?  The Washington P', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 08:00:00', ''),
(29, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LmNubi5jb20vMjAyMS8wNS8xNi91cy9kYWxsYXMtYm95LWZvdW5kLWRlYWQtb24tc3RyZWV0L2luZGV4Lmh0bWzSAVBodHRwczovL2FtcC5jbm4uY29tL2Nubi8yMDIxLzA1LzE2L3VzL2RhbGxhcy1ib3ktZm91bmQtZGVhZC1vbi1zdHJlZXQvaW5kZXguaHRtbA?oc=5', 'A 4-year-old boy was found on a street \\''murdered in a violent act,\\'' Dallas police say - CNN', 'A 4-year-old boy was found on a street \\''murdered in a violent act,\\'' Dallas police say  CNN Man arrested in the death o', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 07:36:00', ''),
(30, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LmVzcG4uY29tL25obC9zdG9yeS9fL2lkLzMxNDU0NTI1L25obC1wbGF5b2Zmcy1kYWlseS0yMDIxLWNyYWlnLWFuZGVyc29uLXJlc2N1ZdIBZ2h0dHBzOi8vd3d3LmVzcG4uY29tL25obC9zdG9yeS9fL2lkLzMxNDU0NTI1L25obC1wbGF5b2Zmcy1kYWlseS0yMDIxLWNyYWlnLWFuZGVyc29uLXJlc2N1ZT9wbGF0Zm9ybT1hbXA?oc=5', 'NHL Playoffs Daily 2021: Craig Anderson to the rescue - ESPN', 'NHL Playoffs Daily 2021: Craig Anderson to the rescue  ESPN Welcome To The 2021 Stanley Cup Playoffs | Hype Video  SPORT', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 06:47:04', ''),
(31, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LmNic25ld3MuY29tL25ld3MvaXNyYWVsLXBhbGVzdGluaWFucy1nYXphLXZpb2xlbmNlLWZsYXJpbmctMjAyMS_SAVBodHRwczovL3d3dy5jYnNuZXdzLmNvbS9hbXAvbmV3cy9pc3JhZWwtcGFsZXN0aW5pYW5zLWdhemEtdmlvbGVuY2UtZmxhcmluZy0yMDIxLw?oc=5', 'Why is violence flaring up in Israel and Gaza? - CBS News', 'Why is violence flaring up in Israel and Gaza?  CBS News Israel-Gaza: Strike collapses building during live BBC report -', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 05:58:02', ''),
(32, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LnNsYXNoZ2Vhci5jb20vZ29vZ2xlLXBob3Rvcy10by1lbmQtZnJlZS11cGxvYWRzLXdoYXQtaXQtbWVhbnMtdG8teW91LTE2NjcyOTU2L9IBXmh0dHBzOi8vd3d3LnNsYXNoZ2Vhci5jb20vZ29vZ2xlLXBob3Rvcy10by1lbmQtZnJlZS11cGxvYWRzLXdoYXQtaXQtbWVhbnMtdG8teW91LTE2NjcyOTU2L2FtcC8?oc=5', 'Google Photos to end free unlimited uploads: What it means to you - SlashGear', 'Google Photos to end free unlimited uploads: What it means to you  SlashGear How to Back Up All the Photos on Your Phone', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 05:03:00', ''),
(33, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LnlhaG9vLmNvbS9uZXdzL3NwYWNleC1ibGFzdGVkLWFub3RoZXItNTItc3RhcmxpbmstMDk0MjQ3OTc1Lmh0bWzSAVVodHRwczovL25ld3MueWFob28uY29tL2FtcGh0bWwvbmV3cy9zcGFjZXgtYmxhc3RlZC1hbm90aGVyLTUyLXN0YXJsaW5rLTA5NDI0Nzk3NS5odG1s?oc=5', 'SpaceX blasted another 52 Starlink internet satellites and 2 payloads into orbit on a Falcon 9 rocket, which landed perf', 'SpaceX blasted another 52 Starlink internet satellites and 2 payloads into orbit on a Falcon 9 rocket, which landed perf', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 04:42:47', ''),
(34, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMicGh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvYmVoaW5kLXRoZS1lcGljLWFwcGxlLXRyaWFsLWlzLWEtYm9vbWluZy1hcHAtbWFya2V0LXdvcnRoLWZpZ2h0aW5nLW92ZXItMTE2MjExNTc0MDXSAQA?oc=5', 'Behind the Epic-Apple Trial Is a Booming App Market Worth Fighting Over - The Wall Street Journal', 'Behind the Epic-Apple Trial Is a Booming App Market Worth Fighting Over  The Wall Street Journal Tech Talk - Epic vs. Ap', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-16 04:30:00', ''),
(35, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vc3BhY2VmbGlnaHRub3cuY29tLzIwMjEvMDUvMTYvc3BhY2V4LXJhbXBzLXVwLWxhdW5jaC1yYXRlLWZpZnRoLWZhbGNvbi05LW1pc3Npb24taW4tdGhyZWUtd2Vla3Mv0gEA?oc=5', 'SpaceX ramps up launch rate with fifth Falcon 9 mission in three weeks – Spaceflight Now - Spaceflight Now', 'SpaceX ramps up launch rate with fifth Falcon 9 mission in three weeks – Spaceflight Now  Spaceflight Now Billion-dollar', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-15 20:50:54', ''),
(36, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9dmRyVUhGdEc2UG_SAQA?oc=5', 'Americans divided on new CDC mask guidance - CBS Evening News', 'Americans divided on new CDC mask guidance  CBS Evening News Local businesses hesitant to ditch mask requirements, despi', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-15 17:50:14', ''),
(37, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMiTmh0dHBzOi8vc2NpdGVjaGRhaWx5LmNvbS90aWFuZ29uZy1jaGluYS1tYXktZ2Fpbi1hLW1vbm9wb2x5LW9uLXNwYWNlLXN0YXRpb25zL9IBUmh0dHBzOi8vc2NpdGVjaGRhaWx5LmNvbS90aWFuZ29uZy1jaGluYS1tYXktZ2Fpbi1hLW1vbm9wb2x5LW9uLXNwYWNlLXN0YXRpb25zL2FtcC8?oc=5', 'Tiangong: China May Gain a Monopoly on Space Stations - SciTechDaily', 'Tiangong: China May Gain a Monopoly on Space Stations  SciTechDaily Kate Rubins - Scientist in Space  NASA Johnson Space', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-15 15:15:16', ''),
(38, '', '', '', NULL, NULL, '', 'https://news.google.com/__i/rss/rd/articles/CBMijQFodHRwczovL3d3dy5vcmxhbmRvc2VudGluZWwuY29tL2Nvcm9uYXZpcnVzL29zLW5lLWZsb3JpZGEtY29yb25hdmlydXMtc2F0dXJkYXktbWF5LTE1LTIwMjEwNTE1LTIwMjEwNTE1LWI0dTV2Z3VvdnJkdGRrYW1seXR0MmFqdGVxLXN0b3J5Lmh0bWzSAZwBaHR0cHM6Ly93d3cub3JsYW5kb3NlbnRpbmVsLmNvbS9jb3JvbmF2aXJ1cy9vcy1uZS1mbG9yaWRhLWNvcm9uYXZpcnVzLXNhdHVyZGF5LW1heS0xNS0yMDIxMDUxNS0yMDIxMDUxNS1iNHU1dmd1b3ZyZHRka2FtbHl0dDJhanRlcS1zdG9yeS5odG1sP291dHB1dFR5cGU9YW1w?oc=5', 'Florida reports 3,319 new COVID-19 infections, 56 more resident fatalities - Orlando Sentinel', 'Florida reports 3,319 new COVID-19 infections, 56 more resident fatalities  Orlando Sentinel Sunday Florida COVID update', 'https://news.google.com/?topic=h&amp;hl=en-US&amp;gl=US&amp;ceid=US:en', 'Top stories - Google News', '2021-05-15 13:25:26', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
